# Site settings
author: Adam Gillespie
title: Forever Behind the Screen 
header-img: img/home-bg.png
email: adam.g.tpt@gmail.com
copyright_name: Adam Gillespie
description: > # this means to ignore newlines until "baseurl:"
  the adventures of learning to code 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  agilles1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
